nelmio_api_doc:
    use_validation_groups: true
    documentation:
        servers:
            - url: http://localhost:8000
              description: API over HTTP

        info:
            title: Test App
            description: This is an awesome app!
            version: 1.0.0

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                User:
                    type: object
                    properties:
                        username:
                            type: string
                            example: test@mail.com
                        password:
                            type: string
                            example: my_password
                    required:
                        - username
                        - password
                Token:
                    type: object
                    properties:
                        token:
                            type: string

                InvalidCredentials:
                    type: object
                    properties:
                        code:
                            type: string
                        message:
                            type: string

        security:
            - Bearer: [ ]

        paths:
            /api/login_check:
                post:
                    tags: [ JWT ]
                    summary: Get jwt
                    requestBody:
                        description: get jwt
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/User'
                        required: true
                    responses:
                        '200':
                            description: Successful operation
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '401':
                            description: Invalid credentials
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/InvalidCredentials'
                        '400':
                            description: Bad request


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc

    models:
        names:
#            - { alias: Application,        type: App\Entity\Application }
            - { alias: Application Created,  type: App\Entity\Application, groups: [ created ] }
            - { alias: Application Show,  type: App\Entity\Application, groups: [ show ] }
            - { alias: Application List,  type: App\Entity\Application, groups: [ list ] }
            - { alias: Application Update,  type: App\Entity\Application, groups: [ update ] }
            - { alias: Application Create,  type: App\Entity\Application, groups: [ create ] }