version: "3.5"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      args:
        - UID=${PUID}
        - GID=${PGID}
        - USER=${PUSER}
        - GROUP=${PGROUP}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www:rw
      - sock_test_php:/var/run
      - /docker

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm8.1
      args:
        - UID=${PUID}
        - GID=${PGID}
        - USER=${PUSER}
        - GROUP=${PGROUP}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=DebugTestPHP"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - sock_test_php:/var/run
#      - ./docker/php-fpm8.1/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /docker

volumes:
  sock_test_php:

