version: "3.5"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      args:
        - UID=${PUID}
        - GID=${PGID}
        - USER=${PUSER}
        - GROUP=${PGROUP}
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www:rw
      - sock_test_php:/var/run
      - /docker

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm8.1
      args:
        - UID=${PUID}
        - GID=${PGID}
        - USER=${PUSER}
        - GROUP=${PGROUP}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=DebugTestPHP"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - database
    volumes:
      - ./:/var/www
      - sock_test_php:/var/run
#      - ./docker/php-fpm8.1/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /docker

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  mailcatcher:
    hostname: mailcatcher
    image: jeanberu/mailcatcher
    ports:
      - ${SMTP_PORT}:1025
      - ${SMTP_WEB_PORT}:1080

volumes:
  sock_test_php:

